name: flutter_car_route_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.7.2

  # Google Maps & Location
  google_maps_flutter: ^2.2.5
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.3.1
  # Networking
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4

  # JSON
  json_annotation: ^4.9.0
  geocoding: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  integration_test:
      sdk: flutter


  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:


  # use the icons in the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/markers/

  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
